language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
  - 14
  - 13
  - 12
  - 11
  - 10
addons:
  sonarcloud:
    organization: "guilhermedelemos-github"
install:
  - yarn install
script:
  - yarn test
  - bash sonar.sh